### ISSUE TITLE
lein servlet uberwar does not create .class files

### ISSUE THREAD

**Issue by gardnervickers** [kumarshantanu/lein-servlet#6]
Not sure what the intended behavior here is, but `lein clean && lein servlet uberwar` will never result in a viable `.war`.

**Comment by kumarshantanu** [comment]
Does the error happen only with any particular setup? Steps to reproduce the issue would be useful. I tried the following, which seems to work:

``` bash
lein new lein-servlet foo
cd foo
lein clean && lein servlet uberwar
jar tvf target/foo-0.1.0-SNAPSHOT.war
```
